/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#0f172a',
        canvas: '#f7f8fa',
        accent: '#10b981',
        'ink-muted': '#475569',
        paper: '#ffffff',
        mist: '#f2f4f6',
        line: '#e2e8f0',
        'accent-soft': '#d1fae5',

        // Stitch Tokens
        'inverse-on-surface': '#f0f1f3',
        primary: '#000000',
        'on-primary-fixed': '#131b2e',
        'surface-bright': '#f8f9fb',
        'surface-container-low': '#f2f4f6',
        'surface-container-high': '#e7e8ea',
        tertiary: '#000000',
        'secondary-fixed-dim': '#4edea3',
        'inverse-primary': '#bec6e0',
        'on-primary-container': '#7c839b',
        'on-secondary-fixed': '#002113',
        'secondary-container': '#6cf8bb',
        'on-tertiary-fixed-variant': '#38485d',
        'outline-variant': '#c6c6cd',
        'primary-container': '#131b2e',
        'on-secondary-fixed-variant': '#005236',
        'surface-dim': '#d9dadc',
        'on-surface-variant': '#45464d',
        secondary: '#006c49',
        'on-tertiary-fixed': '#0b1c30',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        background: '#f8f9fb',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#bec6e0',
        'inverse-surface': '#2e3132',
        'surface-container-highest': '#e1e2e4',
        'primary-fixed': '#dae2fd',
        'surface-tint': '#565e74',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary-container': '#75859d',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#0b1c30',
        'tertiary-fixed': '#d3e4fe',
        'on-secondary-container': '#00714d',
        'on-tertiary': '#ffffff',
        'on-surface': '#191c1e',
        'on-primary': '#ffffff',
        'secondary-fixed': '#6ffbbe',
        'on-error': '#ffffff',
        outline: '#76777d',
        'on-primary-fixed-variant': '#3f465c',
        surface: '#f8f9fb',
        'on-error-container': '#93000a',
        'surface-container': '#edeef0',
        'surface-variant': '#e1e2e4',
        'on-background': '#191c1e'
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem'
      },
      spacing: {
        'container-max': '1280px',
        base: '8px',
        'margin-desktop': '40px',
        'stack-sm': '12px',
        'stack-lg': '48px',
        'stack-md': '24px',
        gutter: '24px',
        'margin-mobile': '16px'
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        data: ['Geist', 'ui-monospace', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'data-tabular': ['Geist', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif']
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'data-tabular': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }]
      }
    },
  },
  plugins: [],
};

