import { motion } from 'framer-motion';
import { useMemo, useState } from 'react';
import { calculateRentersPremium } from '../lib/calculators/rentersInsurance';
import type { Deductible, LiabilityCoverage, PropertyValue } from '../lib/calculators/types';

export default function RentersCalculator({ stateBaseRate, stateName }: { stateBaseRate: number; stateName: string }) {
  const [propertyValue, setPropertyValue] = useState<PropertyValue>(30000);
  const [liabilityCoverage, setLiabilityCoverage] = useState<LiabilityCoverage>(100000);
  const [deductible, setDeductible] = useState<Deductible>(500);
  const [annual, setAnnual] = useState(false);
  const estimate = useMemo(() => calculateRentersPremium({ stateBaseRate, propertyValue, liabilityCoverage, deductible }), [stateBaseRate, propertyValue, liabilityCoverage, deductible]);
  const low = annual ? estimate.low : Math.round(estimate.low / 12); const high = annual ? estimate.high : Math.round(estimate.high / 12); const midpoint = Math.round((low + high) / 2);
  const money = (amount: number) => `$${amount.toLocaleString('en-US')}`;
  const factorText = (multiplier: number) => multiplier === 1 ? 'Baseline' : `${multiplier > 1 ? '+' : ''}${Math.round((multiplier - 1) * 100)}% vs baseline`;

  return <section id="calculator" className="overflow-hidden rounded-xl border border-line bg-paper shadow-xl scroll-mt-24"><div className="h-1.5 bg-accent"/><div className="flex flex-col gap-8 p-6 lg:flex-row lg:gap-16 lg:p-12">
    <div className="flex-1"><span className="field-label text-accent">Localized actuarial model</span><h2 className="mt-1 text-3xl font-semibold tracking-tight text-ink">Estimation Model</h2><p className="mt-2 text-sm text-ink-muted">Adjust coverage limits and deductible to refine your projected premium in {stateName}.</p>
      <div className="mt-8 space-y-7"><div><div className="between"><label className="text-sm font-semibold text-ink">Personal Property Coverage</label><span className="rounded border border-line bg-mist px-2.5 py-1 font-data text-sm font-semibold">{money(propertyValue)}</span></div><input aria-label="Personal property coverage" className="mt-4 h-2 w-full cursor-pointer appearance-none rounded-full bg-line accent-ink" max="50000" min="10000" step="10000" type="range" value={propertyValue} onChange={e => setPropertyValue(Number(e.target.value) as PropertyValue)}/><div className="between mt-2 font-data text-[11px] text-ink-muted"><span>$10,000</span><span>$30,000</span><span>$50,000</span></div></div>
      <div><div className="between"><label className="text-sm font-semibold text-ink">Personal Liability Limit</label><span className="rounded border border-line bg-mist px-2.5 py-1 font-data text-sm font-semibold">{money(liabilityCoverage)}</span></div><input aria-label="Personal liability limit" className="mt-4 h-2 w-full cursor-pointer appearance-none rounded-full bg-line accent-ink" max="500000" min="100000" step="200000" type="range" value={liabilityCoverage} onChange={e => setLiabilityCoverage(Number(e.target.value) as LiabilityCoverage)}/><div className="between mt-2 font-data text-[11px] text-ink-muted"><span>$100,000</span><span>$300,000</span><span>$500,000</span></div></div>
      <div><label className="text-sm font-semibold text-ink">Policy Deductible</label><select aria-label="Policy deductible" className="field-control mt-3" value={deductible} onChange={e => setDeductible(Number(e.target.value) as Deductible)}><option value="500">$500 Deductible (Standard)</option><option value="1000">$1,000 Deductible (Lower Rate)</option><option value="2500">$2,500 Deductible (High Savings)</option></select></div></div>
    </div>
    <div className="flex flex-1 flex-col justify-between rounded-xl border border-line bg-mist p-6 shadow-sm lg:p-8"><div><div className="between"><span className="field-label">Estimated premium range</span><div className="flex rounded border border-line bg-paper p-1 text-xs"><button type="button" onClick={() => setAnnual(false)} className={`rounded px-3 py-1 ${!annual ? 'bg-ink text-paper' : 'text-ink-muted'}`}>Monthly</button><button type="button" onClick={() => setAnnual(true)} className={`rounded px-3 py-1 ${annual ? 'bg-ink text-paper' : 'text-ink-muted'}`}>Annual</button></div></div><motion.div key={`${low}-${high}-${annual}`} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} className="mt-7"><p className="font-data text-4xl font-bold tracking-tight text-ink">{money(low)} – {money(high)}</p><p className="mt-2 flex items-center gap-2 text-sm font-medium text-accent"><span className="h-2 w-2 rounded-full bg-accent"/>Midpoint estimate: {money(midpoint)} {annual ? '/ year' : '/ month'}</p></motion.div><div className="mt-7 border-t border-line pt-5"><p className="field-label">Cost factor breakdown</p><div className="mt-3 space-y-2">{estimate.breakdown.map(item => <div key={item.label} className="between border-b border-line/70 py-2 text-sm"><span className="text-ink-muted">{item.label}</span><span className="font-data font-semibold text-ink">{item.label === 'State base rate' ? money(item.value) : factorText(item.value)}</span></div>)}</div>
</div></div><div className="mt-8 border-t border-line pt-6"><a className="block rounded bg-accent px-5 py-3 text-center text-sm font-semibold text-paper" href="#quotes">Compare Live Quotes</a><p className="mt-3 text-center text-xs leading-5 text-ink-muted">Compare personalized quotes from top-rated insurance providers in under 2 minutes.</p></div></div>
  </div></section>;
}
